version: '3'
services:
    framework-educativo-front:
        container_name: framework-educativo-front
        image: framework-educativo-front:latest
        build: 
            context: https://github.com/tronxi/framework-educativo-front.git#develop
        ports:
            - "80:80"
        env_file: .env
        networks: 
            - framework-educativo-net

    framework-educativo-eureka:
        container_name: framework-educativo-eureka
        image: framework-educativo-eureka:latest
        build: 
            context: https://github.com/tronxi/framework-educativo-eureka.git#develop
        ports:
            - "8761:8761"
        env_file: .env
        networks: 
            - framework-educativo-net

    framework-educativo-gateway:
        container_name: framework-educativo-gateway
        image: framework-educativo-gateway:latest
        build: 
            context: https://github.com/tronxi/framework-educativo-gateway.git#develop
        ports:
            - "8079:8079"
        env_file: .env
        networks: 
            - framework-educativo-net

    framework-educativo-user:
        container_name: framework-educativo-user
        image: framework-educativo-user:latest
        build: 
            context: https://github.com/tronxi/framework-educativo-user.git#develop
        ports:
            - "8081:8081"
        env_file: .env
        networks: 
            - framework-educativo-net

    framework-educativo-subject:
        container_name: framework-educativo-subject
        image: framework-educativo-subject:latest
        build: 
            context: https://github.com/tronxi/framework-educativo-subject.git#develop
        ports:
            - "8082:8082"
        env_file: .env
        networks: 
            - framework-educativo-net
    
    framework-educativo-zuul:
        container_name: framework-educativo-zuul
        image: framework-educativo-zuul:latest
        build: 
            context: https://github.com/tronxi/framework-educativo-zuul.git#develop
        ports:
            - "8070:8070"
        env_file: .env
        networks: 
            - framework-educativo-net

networks: 
    framework-educativo-net:
